### ISSUE TITLE
Client crash on breaking Flint Axe

### ISSUE THREAD

**Issue by Burgersim** [antoinehu/vs-usefulstuff#4]
Hi, my client crashes when my flint axe breaks, idk if it's the mod but the error log seems to indicate that it might be. Maybe something to do with the drop of nuggets on breaking metal stuff, but no nuggets existing or something like that? or a full iniventory? idk, hope you can help tho ^^*

I think I might've found an issue with your mod. When my flint axe breaks my client crashes and the error log indicates this mod. Does it maybe have something to do with the breaking and getting nuggets but there are none for flint? Idk, I'll post the issue on the issue tracker as well.

Running on 64 bit Windows with 16 GB RAM
Game Version: v1.18.1 (Stable)
24/04/2023 18:13:34: Critical error occurred
Loaded Mods: ancienttools@1.5.2, fieldsofgold@2.1.6, HangingOilLamps@1.0.1, hideandfabric@1.3.0, indappledgroves@0.4.9-rc.5, KreaturesAndKritters@1.0.0, moreclasses@1.2.5, primitivesurvival@3.1.7, game@1.18.1, wildcrafttrees@1.1.5, wildcraft@1.6.4, canbeignited@1.1.0, carryon@1.0.0, fromgoldencombs@1.4.16-rc.2, morepiles@1.3.0, petai@1.7.0, claywheel@1.0.1, usefulstuff17@1.1.3, creative@1.18.1, survival@1.18.1, bullseye@2.5.0-rc.1, cats@1.7.0, foxtaming@1.2.0, wolftaming@1.7.1
Involved Harmony IDs: com.jakecool19.usefulstuff.enhancements
System.NullReferenceException: Object reference not set to an instance of an object.
at Vintagestory.API.Common.CollectibleObject.DamageItem_Patch1(CollectibleObject this, IWorldAccessor world, Entity byEntity, ItemSlot itemslot, Int32 amount)
at Vintagestory.API.Common.CollectibleObject.OnBlockBrokenWith(IWorldAccessor world, Entity byEntity, ItemSlot itemslot, BlockSelection blockSel, Single dropQuantityMultiplier) in VintagestoryApi\Common\Collectible\Collectible.cs:line 538
at Vintagestory.Client.NoObf.ClientMain.OnPlayerTryDestroyBlock(BlockSelection blockSelection) in VintagestoryLib\Client\ClientMain.cs:line 1672
at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.ContinueBreakSurvival(BlockSelection blockSelection, Block block, Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 788
at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsBlockSelected(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 595
at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 86
at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 199
at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 785
at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 977
at Vintagestory.Client.GuiScreenRunningGame.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 241
at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 722
at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 625
at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 119
at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 476
at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 452
at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 24/04/2023 09:38:03, Site = , Source = Application Hang, Message = The program Vintagestory.exe version 1.18.1.0 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel.

Process ID: a24

Start Time: 01d9767f164912e6

Termination Time: 11

Application Path: C:\Users\salze\AppData\Roaming\Vintagestory\Vintagestory.exe

Report Id: 2b6b1005-96ed-4e08-bd39-9b769a908beb

Faulting package full name:

Faulting package-relative application ID:

Hang type: Unknown
}
--------------
{ TimeGenerated = 24/04/2023 09:38:00, Site = , Source = Windows Error Reporting, Message = Fault bucket 1348960424135920314, type 5
Event Name: AppHangB1
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.1.0
P3: 6443b447
P4: 387b
P5: 134217728
P6:
P7:
P8:
P9:
P10:

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER97C0.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER97E1.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER97E0.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER97F0.tmp.txt
\\?\C:\Users\salze\AppData\Local\Temp\WEREEE1.tmp.appcompat.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppHang_Vintagestory.exe_2b777c864f7c2d913f171ce6ab9caca0691b40_844f11b8_71ea8d33-c516-4c01-94f1-e9ba1be2a186

Analysis symbol:
Rechecking for solution: 0
Report Id: 2b6b1005-96ed-4e08-bd39-9b769a908beb
Report Status: 268435456
Hashed bucket: 90cca8790cbc4c3d62b8785bd0ae8aba
Cab Guid: 0 }
--------------
{ TimeGenerated = 24/04/2023 09:36:11, Site = , Source = Windows Error Reporting, Message = Fault bucket 1248370421850872525, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.1.0
P3: 10.0.19045.2.0.0
P4:
P5:
P6:
P7:
P8:
P9:
P10:

Attached files:
\\?\C:\Users\salze\AppData\Local\Temp\RDR3568.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER3569.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER3589.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER3589.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER35A9.tmp.txt

These files may be available here:

Analysis symbol:
Rechecking for solution: 0
Report Id: ce0171d5-688a-4983-ba49-ac9805361c75
Report Status: 268435456
Hashed bucket: 14d5118b5bf73c7861531a48d6869acd
Cab Guid: 0 }

**Comment by Burgersim** [comment]
Turns out it was another mod's fault so feel free to close this issue and have a great week :3
