### ISSUE TITLE
EndOfStreamException

### ISSUE THREAD

**Issue by WickedSchnitzel** [antoinehu/vs-usefulstuff#6]
```
[Error] System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.ReadString()
   at UsefulStuff.BlockEntityNameTag.OnReceivedClientPacket(IPlayer player, Int32 packetid, Byte[] data)
   at Vintagestory.Server.ServerSystemBlockSimulation.HandleBlockEntityPacket(Packet_Client packet, ConnectedClient client) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Server\Systems\World\BlockSimulation.cs:line 326
   at Vintagestory.Server.ServerMain.ProcessNetMessage(NetIncomingMessage msg, NetServer mainSocket) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Server\ServerMainNetworking.cs:line 138
```

**Comment by WickedSchnitzel** [comment]
1.18.14
